# Generated by Django 3.1.5 on 2021-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
