# Generated by Django 3.1.5 on 2021-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobat', '0002_auto_20210108_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
