# Generated by Django 3.1.5 on 2021-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobat', '0003_auto_20210108_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
