# Generated by Django 3.1.5 on 2021-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobat', '0004_auto_20210108_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nobat',
            name='name',
            field=models.CharField(default='nothing', max_length=100),
        ),
    ]
