# Generated by Django 3.1.5 on 2021-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobat', '0005_auto_20210108_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
